### ISSUE TITLE
是不是data_illum.h5文件中的数据缺少了一个通道？

### ISSUE THREAD

**Issue by linklist2** [Linfeng-Tang/PIAFusion#2]
您好，非常感谢您的工作！
但是根据提供的百度连接下载[data_illum.h5](https://pan.baidu.com/s/12Xu1Ep7kKwe03HFBQYWkhw?pwd=PIAF).后，
通过调试发现其shape为：
![image](https://user-images.githubusercontent.com/46252413/174439920-001f0df5-91ec-4d99-ac47-b1021683c56b.png)
中间的4感觉少了一个通道，one-hot标签占2个通道，RGB数据3个通道，应该是5个通道感觉才对。
通过代码中的np.transpose(sources, (0, 3, 2, 1))转换后打印了数据：

![image](https://user-images.githubusercontent.com/46252413/174439975-4bd0626a-644b-4103-b607-a62dd38c741d.png)
感觉只有前两列是图片的像素值，后两列是one-hot标签。

**Comment by Linfeng-Tang** [comment]
非常抱歉 在我们最终版本中 我们使用的灰度图像来训练光照感知模型和融合模型，因此正确的数据读取方式为： images = sources[:, :, :, 0:1]， labels = sources[:, 0, 0, 2:4]。感谢你的提醒 我们已经更新了相关代码~

**Comment by Linfeng-Tang** [comment]
感谢你的提问 确实是我们上传了一个旧的版本所导致的，我们已经在尝试将最新的数据文件上传百度云了，上传之后我们会更改相应的链接地址~

**Comment by linklist2** [comment]
好的，期待您的更新
&nbsp;


乐天
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Linfeng ***@***.***&gt;; 
发送时间: 2022年6月18日(星期六) 晚上10:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Linfeng-Tang/PIAFusion] 是不是data_illum.h5文件中的数据缺少了一个通道？ (Issue #2)





 
感谢你的提问 确实是我们上传了一个旧的版本所导致的，我们已经在尝试将最新的数据文件上传百度云了，上传之后我们会更改相应的链接地址~
 
&mdash;

**Comment by linklist2** [comment]
@Linfeng-Tang 好的，期待您的更新

**Comment by Linfeng-Tang** [comment]
已经更新了 你可以重新下载一下试试！

**Comment by linklist2** [comment]
@Linfeng-Tang 非常感谢，已经看到了更新，还有一个疑惑就是这里的h5文件的彩色图是RGB顺序存储的，还是BGR顺序存储的？

**Comment by linklist2** [comment]
![image](https://user-images.githubusercontent.com/46252413/174508271-12634b1f-d53c-40df-bbed-62f60f8c8e75.png)
![image](https://user-images.githubusercontent.com/46252413/174508273-87e621cd-9ce9-4983-935d-e7e3fda8f80b.png)

CMDAF的代码实现也与论文中的公式不符，似乎红框中的sub_ir_vi与sub_vi_ir写反了。
@Linfeng-Tang

**Comment by Linfeng-Tang** [comment]
你加一下我QQ：2458707789， 方便交流。

**Comment by linklist2** [comment]
> 你加一下我QQ：2458707789， 方便交流。

@Linfeng-Tang 已经申请

**Comment by Linfeng-Tang** [comment]
还没有收到你的申请呢？

**Comment by linklist2** [comment]
> 还没有收到你的申请呢？

@Linfeng-Tang 又一次申请了，如果还是没有收到，可以尝试加一下我吗？QQ：2273098543

**Comment by Linfeng-Tang** [comment]
我也向你发送了两次好友申请，不行的话你 加我微信：18774930139
